/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.Proyecto;
import Controlador.Controlador;

import Controlador.Controlador;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.Serializable;

/**
 *
 * @author alemo
 */
public class  CargarProyecto extends javax.swing.JFrame implements Serializable {
    private Controlador controlador;
    DefaultListModel proyectos=new DefaultListModel();
    /**
     * Creates new form CargarProyecto
     */
    public CargarProyecto() {
        initComponents();
        proyectos=new DefaultListModel();
        listaProyectos.setModel(proyectos);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    public void initComponents() {

        jScrollPane1 = new JScrollPane();
        listaProyectos = new JList<>();
        botonAbrir = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("CARGAR PROYECTO");

        jScrollPane1.setViewportView(listaProyectos);

        botonAbrir.setText("CARGAR");

        ActionListener abrirProyectoListener=new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controlador.abrirProyecto();
            }
        };
        botonAbrir.addActionListener(abrirProyectoListener);
/*
        botonAbrir.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {

                botonCargarProyectoActionPerformed(evt);
            }
        });*/
        //Este boton tiene que ser llevado por controlador
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 301, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonAbrir)
                                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botonAbrir, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargarProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargarProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargarProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargarProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CargarProyecto().setVisible(true);
            }
        });
    }
    public void setControlador(Controlador c){
        this.controlador=c;
    }/*
    private void botonCargarProyectoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Proyecto proyectoSeleccionado=controlador.getListaProyectosGuardados().get(listaProyectos.getSelectedIndex());
    }*/

    // Variables declaration - do not modify
    private javax.swing.JButton botonAbrir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaProyectos;
    // End of variables declaration
}
