/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.Serializable;
import javax.swing.*;

/**
 *
 * @author alemo
 */
public class DarAltaTarea extends javax.swing.JFrame implements Serializable {


    /**
     * Creates new form DarAltaTarea
     */
    public DarAltaTarea() {
        initComponents();
        SpinnerNumberModel nm = new SpinnerNumberModel();
        nm.setMaximum(5);
        nm.setMinimum(0);
        spinnerPrioridad.setModel(nm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    public String getEntradaTitulo(){
        return entradaTitulo.getText();
    }

    public JSpinner getSpinnerPrioridad() {
        return spinnerPrioridad;
    }

    public JTextField getEntradaCoste(){
        return entradaCoste;
    }
    public JTextField getEntradaTipoCoste(){
        return entradaTipoCoste;
    }
    public JComboBox getDesplegableTipoFacturacion(){
        return desplegableTipoFacturación;
    }

    public JButton getBotonAnyadirEtiqueta() {
        return botonAnyadirEtiqueta;
    }

    public JButton getBotonCrear() {
        return botonCrear;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public JComboBox<String> getDesplegableInternoExterno() {
        return desplegableInternoExterno;
    }

    public JComboBox<String> getDesplegableTipoFacturación() {
        return desplegableTipoFacturación;
    }

    public JComboBox<String> getDesplegableTipoTarea() {
        return desplegableTipoTarea;
    }

    public JTextField getEntradaAnyadirEtiqueta() {
        return entradaAnyadirEtiqueta;
    }

    public JTextField getEntradaDescripcion() {
        return entradaDescripcion;
    }

    public JTextField getEntradaIdTarea() {
        return entradaIdTarea;
    }

    public JTextField getEntradaResponsable() {
        return entradaResponsable;
    }

    public JLabel getLabelEtiquetas() {
        return labelEtiquetas;
    }

    public JLabel getLabelTipoCoste() {
        return labelTipoCoste;
    }

    public JLabel getSimboloEuro() {
        return simboloEuro;
    }

    public JSpinner getSpinnerNumHoras() {
        return spinnerNumHoras;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        entradaTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        entradaResponsable = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        entradaDescripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        spinnerPrioridad = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        entradaCoste = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        desplegableTipoFacturación = new javax.swing.JComboBox<>();
        botonCrear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        entradaIdTarea = new javax.swing.JTextField();
        spinnerNumHoras = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        desplegableInternoExterno = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        desplegableTipoTarea = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        entradaAnyadirEtiqueta = new javax.swing.JTextField();
        botonAnyadirEtiqueta = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        labelEtiquetas = new javax.swing.JLabel();
        labelTipoCoste = new javax.swing.JLabel();
        entradaTipoCoste = new javax.swing.JTextField();
        simboloEuro = new javax.swing.JLabel();

        jLabel12.setText("jLabel12");

        ActionListener crearListener=new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controlador.crearTarea();
            }
        };
       botonCrear.addActionListener(crearListener);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DAR DE ALTA TAREA");

        jLabel1.setText("Titulo:");

        entradaTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaTituloActionPerformed(evt);
            }
        });

        jLabel2.setText("Responable:");

        entradaResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaResponsableActionPerformed(evt);
            }
        });

        jLabel3.setText("(DNI)");

        entradaDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaDescripcionActionPerformed(evt);
            }
        });

        jLabel4.setText("Descripción:");

        spinnerPrioridad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerPrioridadStateChanged(evt);
            }
        });

        jLabel5.setText("Prioridad:");

        jLabel6.setText("Coste:");

        entradaCoste.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        entradaCoste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaCosteActionPerformed(evt);
            }
        });

        jLabel7.setText("€");

        desplegableTipoFacturación.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarea de consumo interno", "Tarea para clientes", "Tarea urgente" }));



        botonCrear.setText("CREAR");
        /*botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });*/

        jLabel8.setText("ID Tarea:");

        entradaIdTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaIdTareaActionPerformed(evt);
            }
        });

        spinnerNumHoras.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerNumHorasStateChanged(evt);
            }
        });

        jLabel9.setText("Horas:");

        desplegableInternoExterno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Resultado Interno", "Resultado Externo" }));
        desplegableInternoExterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegableInternoExternoActionPerformed(evt);
            }
        });

        jLabel10.setText("Tipo:");

        desplegableTipoTarea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Biblioteca", "Documentación", "Página Web", "Programa" }));
        desplegableTipoTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegableTipoTareaActionPerformed(evt);
            }
        });

        jLabel11.setText("Etiqueta:");

        entradaAnyadirEtiqueta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaAnyadirEtiquetaActionPerformed(evt);
            }
        });
        entradaAnyadirEtiqueta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                entradaAnyadirEtiquetaKeyPressed(evt);
            }
        });

        botonAnyadirEtiqueta.setText("AÑADIR");
        botonAnyadirEtiqueta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnyadirEtiquetaActionPerformed(evt);
            }
        });

        jLabel13.setText("Añadidas:");

        labelEtiquetas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        entradaTipoCoste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaTipoCosteActionPerformed(evt);
            }
        });
        desplegableTipoFacturación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegableTipoFacturacionActionPerformed(evt);
            }
        });

        simboloEuro.setText("€");
        entradaTipoCoste.setVisible(false);
        simboloEuro.setVisible(false);
        labelTipoCoste.setVisible(false);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(63, 63, 63))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel4)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel5)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(spinnerPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(entradaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(entradaResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(entradaDescripcion)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(desplegableTipoFacturación, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(desplegableInternoExterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel8)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(entradaIdTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel11)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(entradaAnyadirEtiqueta)))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel9)
                                                                                .addGap(9, 9, 9)
                                                                                .addComponent(spinnerNumHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jLabel10)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(desplegableTipoTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(4, 4, 4)
                                                                                .addComponent(botonAnyadirEtiqueta)
                                                                                .addGap(12, 12, 12)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel6)
                                                                                        .addComponent(labelTipoCoste))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(entradaCoste, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jLabel7))
                                                                                        .addComponent(entradaTipoCoste)))))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel13)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(labelEtiquetas, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(botonCrear)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(simboloEuro)))
                                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(entradaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2)
                                        .addComponent(entradaResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(entradaDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(spinnerPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addComponent(desplegableTipoFacturación, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(desplegableInternoExterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(28, 28, 28)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel11)
                                                        .addComponent(entradaAnyadirEtiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(botonAnyadirEtiqueta)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(entradaIdTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(spinnerNumHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel9)
                                                        .addComponent(jLabel10)
                                                        .addComponent(desplegableTipoTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(entradaCoste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel7))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(labelTipoCoste)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(entradaTipoCoste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(simboloEuro))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(botonCrear)
                                                .addGap(18, 18, 18))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(labelEtiquetas, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel13))
                                                .addContainerGap())))
        );
        pack();
    }// </editor-fold>

    private void entradaTituloActionPerformed(java.awt.event.ActionEvent evt) {

        // TODO add your handling code here:
    }
    public void desplegableTipoFacturacionActionPerformed(ActionEvent evt) {
        if (getDesplegableTipoFacturacion().getSelectedIndex() == 0) {
            getLabelTipoCoste().setVisible(false);
            getEntradaTipoCoste().setText("0");
            getEntradaTipoCoste().setVisible(false);
            getSimboloEuro().setVisible(false);
        } else {
            getLabelTipoCoste().setVisible(true);
            getEntradaTipoCoste().setVisible(true);
            getSimboloEuro().setVisible(true);
        }
    }

    private void entradaResponsableActionPerformed(java.awt.event.ActionEvent evt) {

        // TODO add your handling code here:
    }

    private void entradaDescripcionActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void spinnerPrioridadStateChanged(javax.swing.event.ChangeEvent evt) {
        // TODO add your handling code here:
    }




    private void entradaCosteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }


/*
    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Double coste=Double.parseDouble(entradaCoste.getText().toString());
        String titulo=entradaTitulo.getText().toString();
        String responsable=entradaResponsable.getText().toString();
        String descrip=entradaDescripcion.getText().toString();
        int prioridad=Integer.parseInt(spinnerPrioridad.getValue().toString());
        int tipoFacturacion=desplegableTipoFacturación.getSelectedIndex(); //Consumo Interno, para clientes, urgente
        int desplegableInternoExterno=this.desplegableInternoExterno.getSelectedIndex();
        String idTarea=entradaIdTarea.getText().toString();
        int numHoras=Integer.parseInt(spinnerNumHoras.getValue().toString());
        int tipoTarea=desplegableTipoTarea.getSelectedIndex(); //Biblioteca, Documentación, etc.
        //Ahora enviar todos estos datos a las clases mediante Modelo y Controlador

        JFrame frame= new JFrame("GUARDAR");
        if(JOptionPane.showConfirmDialog(frame, "¿Seguro que quieres guardar esta tarea?", "GUARDAR",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }*/
    public void setControlador(Controlador c){
        controlador=c;
    }
    private void desplegableInternoExternoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void entradaIdTareaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void spinnerNumHorasStateChanged(javax.swing.event.ChangeEvent evt) {
        // TODO add your handling code here:
    }

    private void desplegableTipoTareaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void entradaAnyadirEtiquetaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void botonAnyadirEtiquetaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        //Añadir etiqueta a lista de etiquetas mediante modelo y controlador.

        labelEtiquetas.setText(labelEtiquetas.getText().toString() + entradaAnyadirEtiqueta.getText().toString()+"\n");
        entradaAnyadirEtiqueta.setText("");

    }

    private void entradaTipoCosteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void entradaAnyadirEtiquetaKeyPressed(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:

    }



    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify
    private javax.swing.JButton botonAnyadirEtiqueta;
    private javax.swing.JButton botonCrear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> desplegableInternoExterno;
    private javax.swing.JComboBox<String> desplegableTipoFacturación;
    private javax.swing.JComboBox<String> desplegableTipoTarea;
    private javax.swing.JTextField entradaAnyadirEtiqueta;
    private javax.swing.JTextField entradaCoste;
    private javax.swing.JTextField entradaDescripcion;

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public JLabel getjLabel13() {
        return jLabel13;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    private javax.swing.JTextField entradaIdTarea;
    private javax.swing.JTextField entradaResponsable;
    private javax.swing.JTextField entradaTipoCoste;
    private javax.swing.JTextField entradaTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelEtiquetas;
    private javax.swing.JLabel labelTipoCoste;
    private javax.swing.JLabel simboloEuro;
    private javax.swing.JSpinner spinnerNumHoras;
    private javax.swing.JSpinner spinnerPrioridad;
    private Controlador controlador;
    // End of variables declaration
}
