/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.Persona;
import Controlador.Controlador;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.Serializable;
import java.util.ArrayList;
import Controlador.*;
/**
 *
 * @author alemo
 */
public class EditarTarea extends javax.swing.JFrame implements Serializable {

    /**
     * Creates new form EditarTarea
     */

    public ControladorInterfaz controlador;

    public void setControlador(ControladorInterfaz c){
        controlador=c;
    }

    public void actualizarPersonas(ArrayList<Persona> listPersonas){
        DefaultListModel personas=new DefaultListModel();
        personas.addAll(listPersonas);
        this.listaPersonas.setModel(personas);
    }

    public void actualizarPersonasEspecificas(ArrayList<Persona> listEspec){
        DefaultListModel personas=new DefaultListModel();
        personas.addAll(listEspec);
        this.listaPersonasAsignadas.setModel(personas);
    }

    public EditarTarea() {
        initComponents();
    }

    public JButton getBotonCerrar() {
        return botonCerrar;
    }

    public void setBotonCerrar(JButton botonCerrar) {
        this.botonCerrar = botonCerrar;
    }

    public JButton getBotonDarBajaTarea() {
        return botonDarBajaTarea;
    }

    public void setBotonDarBajaTarea(JButton botonDarBajaTarea) {
        this.botonDarBajaTarea = botonDarBajaTarea;
    }

    public JButton getBotonQuitarPersona() {
        return botonQuitarPersona;
    }

    public void setBotonQuitarPersona(JButton botonQuitarPersona) {
        this.botonQuitarPersona = botonQuitarPersona;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JList<String> getListaPersonas() {
        return listaPersonas;
    }

    public void setListaPersonas(JList<String> listaPersonas) {
        this.listaPersonas = listaPersonas;
    }

    public JButton getBotonAnyadirPersona() {
        return botonAnyadirPersona;
    }

    public void setBotonAnyadirPersona(JButton botonAnyadirPersona) {
        this.botonAnyadirPersona = botonAnyadirPersona;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaPersonas = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        botonAnyadirPersona = new javax.swing.JButton();
        botonQuitarPersona = new javax.swing.JButton();
        botonDarBajaTarea = new javax.swing.JButton();
        botonCerrar = new javax.swing.JButton();
        labelError = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaPersonasAsignadas = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaPersonas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane1.setViewportView(listaPersonas);

        jLabel1.setText("PERSONAS");

        botonAnyadirPersona.setText("AÑADIR PERSONA");

        botonQuitarPersona.setText("QUITAR PERSONA");

        botonDarBajaTarea.setText("DAR DE BAJA TAREA");

        botonCerrar.setText("CERRAR");

        ActionListener anyadirListener=new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controlador.anyadirPersonaATarea();
            }
        };
        botonAnyadirPersona.addActionListener(anyadirListener);

        ActionListener cerrarListener=new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controlador.cerrarEditarTarea();
            }
        };
        botonCerrar.addActionListener(cerrarListener);

        ActionListener quitarPersonaListener=new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controlador.quitarPersona();
            }
        };
        botonQuitarPersona.addActionListener(quitarPersonaListener);

        ActionListener finalizadaListener=new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controlador.setTareaFinalizada();
            }
        };
        botonDarBajaTarea.addActionListener(finalizadaListener);



        listaPersonasAsignadas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane2.setViewportView(listaPersonasAsignadas);

        jLabel2.setText("PERSONAS ASIGNADAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(botonDarBajaTarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(botonQuitarPersona, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(botonAnyadirPersona, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(labelError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addGap(150, 150, 150))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(11, 11, 11)
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(13, 13, 13)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(botonCerrar, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addGap(31, 31, 31))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(60, 60, 60)
                                                .addComponent(botonAnyadirPersona)
                                                .addGap(21, 21, 21)
                                                .addComponent(botonQuitarPersona)
                                                .addGap(18, 18, 18)
                                                .addComponent(botonDarBajaTarea)
                                                .addGap(18, 18, 18)
                                                .addComponent(labelError)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(42, 42, 42)
                                                                .addComponent(botonCerrar))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(33, 33, 33)
                                                                .addComponent(jLabel2))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>





    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public JLabel getLabelError() {
        return labelError;
    }

    public JList<String> getListaPersonasAsignadas() {
        return listaPersonasAsignadas;
    }

    // Variables declaration - do not modify
    private javax.swing.JButton botonAnyadirPersona;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonDarBajaTarea;
    private javax.swing.JButton botonQuitarPersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelError;
    private javax.swing.JList<String> listaPersonas;
    private javax.swing.JList<String> listaPersonasAsignadas;
    // End of variables declaration
}
