/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import Controlador.*;

/**
 *
 * @author alemo
 */
public class MostrarDatosTarea extends javax.swing.JFrame implements Vista {

    /**
     * Creates new form MostrarDatosTarea
     */
    public MostrarDatosTarea() {
        initComponents();
    }

    public void setBotonSalir(JButton botonSalir) {
        this.botonSalir = botonSalir;
    }

    public void setLabelCoste(JLabel labelCoste) {
        this.labelCoste = labelCoste;
    }

    public void setLabelDescripcion(JLabel labelDescripcion) {
        this.labelDescripcion = labelDescripcion;
    }

    public void setLabelEtiquetas(JLabel labelEtiquetas) {
        this.labelEtiquetas = labelEtiquetas;
    }

    public void setLabelID(JLabel labelID) {
        this.labelID = labelID;
    }

    public void setLabelNumHoras(JLabel labelNumHoras) {
        this.labelNumHoras = labelNumHoras;
    }

    public void setLabelPrioridad(JLabel labelPrioridad) {
        this.labelPrioridad = labelPrioridad;
    }

    public void setLabelResponsable(JLabel labelResponsable) {
        this.labelResponsable = labelResponsable;
    }

    public void setLabelResultado(JLabel labelResultado) {
        this.labelResultado = labelResultado;
    }

    public void setLabelTipo(JLabel labelTipo) {
        this.labelTipo = labelTipo;
    }

    public void setLabelTipoConsumo(JLabel labelTipoConsumo) {
        this.labelTipoConsumo = labelTipoConsumo;
    }

    public void setLabelTitulo(JLabel labelTitulo) {
        this.labelTitulo = labelTitulo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        responsable = new javax.swing.JLabel();
        descripcion = new javax.swing.JLabel();
        prioridad = new javax.swing.JLabel();
        tipoConsumo = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        numhoras = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        etiquetas = new javax.swing.JLabel();
        coste = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();
        labelID = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        labelResponsable = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        labelNumHoras = new javax.swing.JLabel();
        labelPrioridad = new javax.swing.JLabel();
        labelTipoConsumo = new javax.swing.JLabel();
        labelResultado = new javax.swing.JLabel();
        labelTipo = new javax.swing.JLabel();
        labelCoste = new javax.swing.JLabel();
        labelEtiquetas = new javax.swing.JLabel();

        labelID.setText("labelID");

        labelTitulo.setText("labelTitulo");

        labelResponsable.setText("labelResponsable");

        labelDescripcion.setText("labelDescripcion");

        labelNumHoras.setText("labelnumhoras");

        labelPrioridad.setText("labelprioridad");

        labelTipoConsumo.setText("label tipo consumo");

        labelResultado.setText("label resultado");

        labelTipo.setText("label tipo");

        labelCoste.setText("coste");

        labelEtiquetas.setText("");

        jLabel12.setText("jLabel12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DATOS TAREA");

        titulo.setText("Título: ");

        responsable.setText("Responsable: ");

        descripcion.setText("Descripción: ");

        prioridad.setText("Prioridad: ");

        tipoConsumo.setText("Tipo de Consumo: ");

        resultado.setText("Resultado: ");

        ID.setText("ID: ");

        numhoras.setText("Número de horas: ");

        tipo.setText("");

        etiquetas.setText("Etiquetas:");

        coste.setText("Coste: ");

        botonSalir.setText("VOLVER");

        ActionListener cerrarMostrarTareaListener=new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controlador.cerrarVerTarea();
            }
        };
        botonSalir.addActionListener(cerrarMostrarTareaListener);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonSalir)
                                .addGap(24, 24, 24))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(descripcion)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelDescripcion)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(titulo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelTitulo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                                                .addComponent(responsable)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelResponsable)
                                                .addGap(89, 89, 89))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(coste)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(labelCoste))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(etiquetas)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(labelEtiquetas))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(tipo)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(labelTipo))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(ID)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(labelID))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(resultado)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(labelResultado))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(tipoConsumo)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(labelTipoConsumo))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(prioridad)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(labelPrioridad)
                                                                .addGap(73, 73, 73)
                                                                .addComponent(numhoras)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(labelNumHoras)))
                                                .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ID)
                                        .addComponent(labelID))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(titulo)
                                        .addComponent(responsable)
                                        .addComponent(labelTitulo)
                                        .addComponent(labelResponsable))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(descripcion)
                                        .addComponent(labelDescripcion))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(prioridad)
                                        .addComponent(numhoras)
                                        .addComponent(labelNumHoras)
                                        .addComponent(labelPrioridad))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tipoConsumo)
                                        .addComponent(labelTipoConsumo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(resultado)
                                        .addComponent(labelResultado))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tipo)
                                        .addComponent(labelTipo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(coste)
                                        .addComponent(labelCoste))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(etiquetas)
                                        .addComponent(labelEtiquetas))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonSalir)
                                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel etiquetas;
    private javax.swing.JLabel coste;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel responsable;
    private javax.swing.JLabel descripcion;
    private javax.swing.JLabel prioridad;
    private javax.swing.JLabel tipoConsumo;
    private javax.swing.JLabel resultado;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel numhoras;
    private javax.swing.JLabel tipo;
    private javax.swing.JLabel labelCoste;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelEtiquetas;
    private javax.swing.JLabel labelID;

    public JLabel getLabelCoste() {
        return labelCoste;
    }

    public void setControlador(ControladorInterfaz c){
        controlador=c;
    }

    public JLabel getLabelDescripcion() {
        return labelDescripcion;
    }

    public JLabel getLabelEtiquetas() {
        return labelEtiquetas;
    }

    public JLabel getLabelID() {
        return labelID;
    }

    public JLabel getLabelNumHoras() {
        return labelNumHoras;
    }

    public JLabel getLabelPrioridad() {
        return labelPrioridad;
    }

    public JLabel getLabelResponsable() {
        return labelResponsable;
    }

    public JLabel getLabelResultado() {
        return labelResultado;
    }

    public JLabel getLabelTipo() {
        return labelTipo;
    }

    public JLabel getLabelTipoConsumo() {
        return labelTipoConsumo;
    }

    public JLabel getLabelTitulo() {
        return labelTitulo;
    }
    public JButton getBotonSalir() {
        return botonSalir;
    }

    private javax.swing.JLabel labelNumHoras;
    private javax.swing.JLabel labelPrioridad;


    private javax.swing.JLabel labelResponsable;
    private javax.swing.JLabel labelResultado;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JLabel labelTipoConsumo;
    private javax.swing.JLabel labelTitulo;
    private ControladorInterfaz controlador;
    // End of variables declaration
}
